

  const Tips = {
    blogText: "Here is where you get comments on each section of the CV, e.g. you click on the photo and it gives you tips on how it should look like",
    LinkedInBlogText: "Detaild types and suggestions for every field",


    WebtipsHeader: 
    "Write your resume in the language that you would use at your workplace. This is a great chance to show the company’s representatives that you can express yourself.Tailor the CV according to job you’re applying for. There is no ‘one size fits all’ CV – so always adapt itbefore applying to a job.Write a short intro that truly represents you –not cheesy quotes, but something you truly believe in. Don’t put overused buzzwords, describe yourself and your capabilities with your own vocabulary.",
    WebtipsPhoto :"Your photo should be professional. It’s better to send a CV without a photo, that with one that makesyou seem unserious.",
    WebtipsWorkExpirience: 
    "Write your previous job experience and if you’re currently working, your current job titles. Explain your responsibilities and projects and list the tech stack and products/projects you worked on. If you were working in a team, let the recruiter know what your role was.",
    WebtipsEdication: 
    "Education is an important section – but be sure to select only what is relevant to the job you’re applying for.     Write about your university degrees, relevant courses and if you have any publications, but skip the high and elementary school. Don’t be afraid to include a “Informal Education” section, where you can list all the courses, podcasts webinars that you used to teach yourself about software development. Don’t include everything – just the education that is relevant and necessary for the position you are applying for.",
    WebtipsSkils: 
    "Showcase your tech stack. List the stack under every previous project you have worked on, or showcase your projects on GitHub. The easiest way to do this is to list the stack under a previous project that you have worked on. Another way is to showcase your projects on GitHub.",
    WebtipsInfos: 
    "Email, phone number and date of birth are the practical part of the assembly of a CV. Enter your professional email address, preferably on Gmail. Your city of living is an information that interests your potential employers. But don’t leave your home address. Leave a link to your LinkedIn profile. If you have proof of your previous job experiences online, link that too.",
    WebtipsAchivmentsInterests:"Dates – a time frame in which you have been on a certain job title. If you are still working there, leave a hyphen ( - ). Leave your most recent experience first, and the oldest ones last. Don’t be afraid to include a “Informal Education” section, where you can list all the courses, podcasts and webinars that you used to teach yourself about software development. Don’t include everything – just the education that is relevant and necessary for the position you are applying for. Tip: Use Action verbs to demonstrate your experience. Examples include: “applied”, “improved”,“implemented” etc.",

    DigitalMarketingtipsHeader: "Write your resume in the language that you would use at your workplace. This is a great chance to show the company’s representatives that you can express yourself.Tailor the CV according to job you’re applying for. There is no ‘one size fits all’ CV – so always adapt itbefore applying to a job.Write a short intro that truly represents you –not cheesy quotes, but something you truly believe in. Don’t put overused buzzwords, describe yourself and your capabilities with your own vocabulary.",
    DigitalMarketintipsHeader:"Write your resume in the language that you would use at your workplace. This is a great chance to show the company’s representatives that you can express yourself. Put a photo that looks professional – made with a good camera and showing you in a warm light. It’s better to send a CV without a photo, than a photo that makes you seem unprofessional. Know your unique value proposition and communicate it effectively. You need a personal tagline that will help you stand out from everyone else. This line should be the first impression the hiring manager will get from you. E.g. if you’re a Content Writer, don’t just say ‘’I’m a great content writer’’. Be creative and say why they should hire you to handle their content.",
    DigitalMarketingtipsEducation:"Under education, list only the relevant studies and courses, like university degree or Digital Marketing Academy. Don’t write where you went to high school.",
    DigitalMarketingtipsWorkExpirience:"List the job experiences that are relevant to the position you’re applying for. If you’re currently working, your current job titles. Explain your responsibilities and projects and list the strategies and projects you created or worked on. Tailor your CV to the company and position you’re applying for. Highlight the keywords from the job specification on your CV. For example, if you’re applying for an e-commerce role, include keywords such as ‘’Conversion, bounce rate and Google Analytics’’.Talk about campaigns you worked on, the budget you had, how it benefited the company etc. This will help recruiters learn how you could benefit them based on your past experience.",
    DigitalMarketingtipsAchievmens:"Tip: Highlight the key achievements you have presented on your CV so the hiring manager can catch them very quickly.",
    DigitalMarketingtipsSKils:"Be specific about the skills, tech and tools you used, and what your role was if you’re listing group projects. Specify coding languages, libraries etc. Make sure you use keywords that will put the focus on your best skills. If an HR/recruiter just scans your CV, they will catch their attention. Highlight terms like “Python” or “Machine learning”. Space is limited, so don’t waste t on soft skills like leadership or communication.",
    DigitalMarketingtipsLanguages:"All languages, even those you don’t speak fluently, can help you get a certain position. It’s good to use expressions such as “fluent in”, “speaking level of”, “native language” and similar.",
    
    DataSciencetipsPhoto:"Put a photo made with a good camera. It’s better to send a CV without a photo, if you were planning on cropping yourself from a group photo from a dinner with friends, or a selfie in you room.",
    DataSciencetipsWorkExpirience:"Write your previous job experience, and if you’re currently working, your current job title. Explain your responsibilities and projects and list the tech stack and products/projects you worked on. If you were working in a team, let the recruiter know what your role was.",
    DataSciencetipsEdication:"Let the recruiter know about your education, but only write the important parts – skip the high school and elementary, stick to the university degrees and courses relevant to the job you’re applying for.",
    DataSciencetipsProjectsAndPublication: "Let the recruiter know about your education, but only write the important parts – skip the high school and elementary, stick to the university degrees and courses relevant to the job you’re applying for.",
    DataSciencetipsSkils:"Be specific about the skills, tech and tools you used, and what your role was if you’re listing group projects. Specify coding languages, libraries etc. Make sure you use keywords that will put the focus on your best skills. If an HR/recruiter just scans your CV, they will catch their attention. Highlight terms like “Python” or “Machine learning”. Space is limited, so don’t waste t on soft skills like leadership or communication.",
    DataSciencetipsLanguages:"All languages, even those you don’t speak fluently, can help you get a certain position. It’s good to use expressions such as “fluent in”, “speaking level of”, “native language” and similar.",
    DataSciencetipsInfos:"Email, phone number and date of birth are the practical part of the assembly of a CV. Enter your professional email address, preferably on Gmail. Your city of living is an information that interests your potential employers. Don’t leave your home address.",
    DataSciencetipsInformalEducation:"Don’t be afraid to include a “Informal education” where you can list all the courses, conferences, workshops and webinars that you used to teach yourself about digital marketing. Don’t include everything – just the education that is relevant and necessary for the position you are applying for.",

    DesigntipsPhoto: "Write your resume in the language that you would use at your workplace. This is a great chance to show the company’s representatives that you can express yourself.Put a photo in a circle frame. It should be professional – made with a good camera and showing you in a warm light. It’s better to send a CV without a photo, than with one that makes you seem unprofessional.One CV isn’t suitable for every job position. Adapt your CV for the job position you’re applying for. Write a short intro that truly represents you – not a cheesy quote, but something you truly believe in.",
    DesignWorkExpirience: "Describe every job experience with a few words about your most relevant responsibilities and projects connected to the title you’re applying for.List relevant education, including workshops or lectures you have visited. If you have a bachelor in Sports, and now you are applying as a designer because you finished a course, the course should be the highest in your “education” section. Don’t put in high and elementary school.",
    DesignEdication: "List relevant education, including workshops or lectures you have visited. If you have a bachelor in Sports, and now you are applying as a designer because you finished a course, the course should be the highest in your “education” section. Don’t put in high and elementary school.",
    DesigntipsSkils: "List all the skills, tools and technologies that you know well. Tip: Play with the font size. The visual part of the CV is also important, so use different colors anddimensions.",
    DesigntipsInfos: "Email, phone number and date of birth are the practical part of the assembly of a CV. Enter your professional email address, preferably on Gmail. Your city of living is an information that interests your potential employers. Don’t leave your home address.",


    WebDevelopmentLinkedInHeader:"Make sure that your title matches your skills. E.g., if you’re an entry level PHP developer, don’t say that you’re a PHP Expert. Skip the abbreviations and titles – keep it short and modest.",
    DataScienceLinkedInHeader:"Make sure that your title matches your skills. E.g., if you’re an entry level Data Scientist, don’t say that you’re a Data Science Expert. Skip the abbreviations and titles – keep it short and modest.",
    DigitalMarketingLinkedInHeader: "Make sure that your title matches your skills. E.g., if you’re an entry level PPC specialist, don’t say that you’re a PPC Expert. Skip the abbreviations and titles – keep it short and modest.",
    DesignLinkedInHeader:"Make sure that your title matches your skills. E.g., if you only finished an academy or course, don’t say you are a Graphic Design Expert. Skip the abbreviations and titles – keep it short and modest.",
    LinledInAbout:"Be concise and easy to understand. Don’t use overdone motivational quotes about work ethics and inspiration, try to make the ‘about’ section as personal and as reflective of you as possible.",
    LinkedInWorkexpirience: "Explain every work experience you’ve had in detail – what were your obligations and tasks, what was your job title, which technologies and tools did you use etc. List the experiences that aren’t connected to your current profession. Volunteering at a local community center, summer jobs, projects you were a part of, pro bono work you did to improve your skills and gain experience – everything counts. It serves as proof to your work ethics and adaptability. Tip: If you have no experience and education to build up your profile, do some pro bono work or volunteer. You can help someone, and at the same time enrich your portfolio.",
    LinkedInEducation:"Under education, list all the formal and non-formal education you have, with focus on the education that is relevant to your current title. For example, if you put Brainster Digital Marketing Academy as an education, list all the modules and projects you have worked on. Make sure to list your major and bachelor/master/doctor thesis subject under the university education. Tip: Add connections from the same field of work as you; even people you don’t know personally. That way, recruiters have a bigger chance of coming across your profile.Put in the skills you are most experienced in, so you can be endorsed from other people.Tip: Ask friends and coworkers to endorse you.List all your relevant accomplishments. Don’t say you have a black belt in karate, but mention an award or relevant campaign.",
    LinkedInArtikels: "Use the new “Open for business” feature. State your area of expertise and industry, to let recruiters know they can reach you. Don’t write in things that you wouldn’t like to happen. For example, if you say you work good under pressure, employers might have an ace up their sleeve when stacking a lot of work with a short deadline,because you said so. Value your skills and free time accordingly.",

    LaikaEmail:"Tip: Make sure you leave an email that you check regularly",  
    LaikaPortofolio:"Link all your social media and portfolios you want companies and recruiters to be able to see (LinkedIn Facebook, Stack Overflow, GitHub, your personal website etc.) Be realistic when choosing the reason why you have a portfolio on Laika. This will help recruiters know whether you are suitable for the position on the long run.",
    LaikaSkils:"*You can only pick 1 industry out of the given 9 (Software Engineering, Design, Marketing and Communication, Data Science, IT and Sysadmin, Sales and Business Development, HR and Recruitment, Project and Product Management, Customer Support). *You can pick up to 5 options in the Expertise field. Make sure your choices are realistic and they truly reflect the skills you are most confident in. *Choose up to 8 technologies, but make sure you really know their ins and outs. The matching algorithm connects you to companies whose job openings have precise technologies listed.*Please be honest when selecting the level of your experience",
    LaikaWorkExpirience:"Work experience is not mandatory, but it helps companies know what kind of experience and in which industry you have.",
    LaikaEducation:"Education is also not mandatory, but it adds weight to your portfolio if you have any academic knowledge.",
    LaikaSalary:"*Select your desired salary. Don’t try to be too accessible, but please be realistic – make sure you desired salary is in accordance to your experience. *You can choose multiple choices for your desired job plan *You can choose out of four locations, or multiple *You can choose between a job in office, remote, or both. *Let the companies know what is your current job title. *Be honest about the motivation behind looking for a new opportunity. This will help us and the companies searching for new employees."

}

 export default Tips;
